const payload=window.quantumJourney;
let legIndex=0,requestID=0,routeNote='点间示意 · 选择汽车或步行可尝试规划路线';
function activeLeg(){return payload.legs[legIndex]||{from:0,to:0,title:payload.stops[0].name};}
function makeSegments(){const l=activeLeg(),a=payload.stops[l.from],b=payload.stops[l.to];return ['飞机','火车','汽车','步行'].map((mode,i)=>({mode,title:l.title||b.name+'，把脚步放慢',route:a.name+' → '+b.name+' · 点间示意',points:[a.coordinate,b.coordinate],level:i===0?1:3}));}
let segments=makeSegments();
const focus=payload.stops[0].coordinate;
const levels=[{center:focus,zoom:1.4,pitch:0,name:'把世界，走成回忆。',sub:(payload.destination||payload.title)+(payload.unlocatedCount?' · '+payload.unlocatedCount+' 个地点待定位':'')},{center:focus,zoom:4.5,pitch:0,name:'从世界的一角出发。',sub:'国家视角 · 拖动探索'},{center:focus,zoom:10,pitch:30,name:'走进这座城。',sub:payload.destination||'城市视角'},{center:focus,zoom:14,pitch:45,name:(payload.destination||payload.stops[0].name)+'，把脚步放慢。',sub:'区域视角 · 留一点时间给偶遇'},{center:focus,zoom:16,pitch:55,name:payload.stops[0].name,sub:'把眼前的风景，收进旅行手记。'}];
document.querySelectorAll('[data-level]').forEach((b,i)=>b.textContent=['地球','国家','城市','区域','地点'][i]);
const legSelect=document.querySelector('#leg');payload.legs.forEach((leg,i)=>{const option=document.createElement('option');option.value=i;option.textContent=(i+1)+' · '+payload.stops[leg.from].name+' → '+payload.stops[leg.to].name;legSelect.append(option);});
function requestRoad(){routeNote='点间示意 · 非实际道路';const s=segments[mode];s.points=[payload.stops[activeLeg().from].coordinate,payload.stops[activeLeg().to].coordinate];map.getSource('journey').setData(line());s.route=payload.stops[activeLeg().from].name+' → '+payload.stops[activeLeg().to].name+' · 点间示意';const id=++requestID;status();if(payload.legs.length&&(mode===2||mode===3)){routeNote='正在寻找'+(mode===2?'道路':'步行')+'路线…';status();window.webkit?.messageHandlers.journey.postMessage({type:'route',leg:legIndex,mode:mode===2?'car':'walk',requestID:id});}}
window.applyJourneyRoute=result=>{if(result.requestID!==requestID)return;if(Array.isArray(result.points)&&result.points.length>1){segments[mode].points=result.points;segments[mode].route=payload.stops[activeLeg().from].name+' → '+payload.stops[activeLeg().to].name+' · '+(mode===2?'道路规划':'步行规划');routeNote='Apple Maps 规划 · 非实际走过的 GPS 轨迹';map.getSource('journey').setData(line());map.setPaintProperty('journey-line','line-dasharray',[1,0]);overview();}else{routeNote='该路段暂无可用路线，保留点间示意';}status();};
legSelect.onchange=()=>{pause();legIndex=+legSelect.value;segments=makeSegments();choose(mode);};
function position(points,t){t=Math.max(0,Math.min(1,t));const lengths=points.slice(1).map((b,i)=>{const a=points[i],dx=((b[0]-a[0]+540)%360)-180;return Math.hypot(dx*Math.cos((a[1]+b[1])*Math.PI/360),b[1]-a[1]);});const total=lengths.reduce((a,b)=>a+b,0);let distance=t*total;for(let i=0;i<lengths.length;i++){if(distance<=lengths[i]||i===lengths.length-1){const u=lengths[i]?distance/lengths[i]:0,a=points[i],b=points[i+1],dx=((b[0]-a[0]+540)%360)-180;return [((a[0]+dx*u+540)%360)-180,a[1]+(b[1]-a[1])*u];}distance-=lengths[i];}return points[0];}
const $=s=>document.querySelector(s),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let map,mode=3,level=0,progress=0,playing=false,last=0,frame,marker;
const tripSheet=$('#trip-sheet'),exploreSheet=$('#explore-sheet');
$('#trip-open').onclick=()=>tripSheet.showModal();$('#location-open').onclick=()=>exploreSheet.showModal();
document.querySelectorAll('.sheet-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
for(const sheet of [tripSheet,exploreSheet])sheet.addEventListener('click',e=>{if(e.target===sheet){const r=sheet.getBoundingClientRect();if(e.clientY<r.top||e.clientX<r.left||e.clientX>r.right)sheet.close();}});
function overview(){if(!map?.getSource('journey'))return;const pts=segments[mode].points;map.stop();map.setPadding({top:0,bottom:0,left:0,right:0});map.setPitch(0);map.setBearing(0);map.fitBounds([[Math.min(...pts.map(p=>p[0])),Math.min(...pts.map(p=>p[1]))],[Math.max(...pts.map(p=>p[0])),Math.max(...pts.map(p=>p[1]))]],{padding:{top:100,bottom:150,left:55,right:55},maxZoom:16,pitch:0,bearing:0,duration:reduced?0:1000});}
$('#close').onclick=()=>window.webkit?.messageHandlers.journey.postMessage({type:'close'});
function pause(){playing=false;$('#play').textContent='▶';$('#play').setAttribute('aria-label','播放旅程');cancelAnimationFrame(frame);}
function status(){const s=segments[mode];$('#segment').textContent=s.title;$('#dock-title').textContent=s.title;document.querySelector('.chapter').textContent='JOURNEY / '+String(legIndex+1).padStart(2,'0');document.querySelector('.day-number').textContent=String(legIndex+1).padStart(2,'0');$('#route').textContent=s.route;$('#detail').textContent=payload.legs.length?s.mode+' · '+(legIndex+1)+' / '+payload.legs.length:'地点位置 · 暂无可回放路段';$('#route').textContent=s.route;document.querySelector('.route-note').textContent=routeNote;$('#progress').value=progress*1000;$('#time').textContent='00:'+String(Math.floor(progress*16)).padStart(2,'0')+' / 00:16';document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.mode)===mode));}
function setLevel(n){level=n;const l={...levels[n],center:payload.stops[activeLeg().to].coordinate};map.flyTo({...l,bearing:n>2?-25:0,duration:reduced?0:1700,essential:false,padding:{top:80,bottom:145,left:0,right:0}});$('#heading').textContent=n===4?payload.stops[activeLeg().to].name:l.name;$('#location-label').textContent=['地球 · 旅行手记','国家视角','城市视角','区域视角',payload.stops[activeLeg().to].name][n];$('#subtitle').textContent=l.sub;document.querySelectorAll('[data-level]').forEach(b=>b.setAttribute('aria-current',Number(b.dataset.level)===n));$('#drill').textContent=['查看国家视角 ↗','查看城市视角 ↗','查看区域视角 ↗','到达地点 ↗','回到地球 ↗'][n];}
function line(){return {type:'Feature',properties:{},geometry:{type:'LineString',coordinates:segments[mode].points}};}
function choose(n){tripSheet.close();pause();mode=n;progress=0;status();map.getSource('journey').setData(line());map.setPaintProperty('journey-line','line-dasharray',[1,1.5]);setLevel(segments[n].level);overview();requestRoad();map.triggerRepaint();}
function tick(now){if(!playing)return;progress=Math.min(1,progress+(now-last)/16000);last=now;status();map.triggerRepaint();if(progress===1){pause();return;}frame=requestAnimationFrame(tick);}
status();
try{
const [M,T]=await Promise.all([import('https://unpkg.com/maplibre-gl@6.11.2/dist/maplibre-gl.mjs'),import('https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js')]);
M.setWorkerUrl('https://unpkg.com/maplibre-gl@6.11.2/dist/maplibre-gl-worker.mjs');
map=new M.Map({container:'map',style:'https://tiles.openfreemap.org/styles/positron',center:levels[0].center,zoom:levels[0].zoom,attributionControl:{compact:true},canvasContextAttributes:{antialias:true},maxPitch:70});
const timeout=setTimeout(()=>{window.webkit?.messageHandlers.journey.postMessage({type:'error',message:'底图加载超时，请重试或使用离线位置视图。'});},25000);
map.on('error',event=>console.warn('Travel map resource:',event.error));
map.on('style.load',()=>{
map.setProjection({type:'globe'});
for(const layer of map.getStyle().layers){if(layer.type==='symbol'&&layer.layout?.['text-field'])map.setLayoutProperty(layer.id,'text-field',['coalesce',['get','name:zh'],['get','name:latin'],['get','name']]);if(layer.type==='background')map.setPaintProperty(layer.id,'background-color','#f7f5ef');if(layer.id==='water')map.setPaintProperty(layer.id,'fill-color','#bcd9dd');if(layer.id==='park'||layer.id==='landcover_wood')map.setPaintProperty(layer.id,'fill-color','#d6e6cf');}
map.addLayer({id:'little-buildings',source:'openmaptiles','source-layer':'building',type:'fill-extrusion',minzoom:14,paint:{'fill-extrusion-color':'#e4dcca','fill-extrusion-height':['coalesce',['get','render_height'],8],'fill-extrusion-base':['coalesce',['get','render_min_height'],0],'fill-extrusion-opacity':.8}});
map.addSource('journey',{type:'geojson',data:line()});map.addLayer({id:'journey-line',type:'line',source:'journey',paint:{'line-color':'#3f7278','line-width':4,'line-opacity':.75,'line-dasharray':[1,1.5]}});
const scene=new T.Scene(),camera=new T.Camera();scene.add(new T.AmbientLight(0xffffff,2.3));const light=new T.DirectionalLight(0xffffff,3);light.position.set(-30,80,40);scene.add(light);
const models=[];
function box(g,color,x,y,z,w,h,d){const o=new T.Mesh(new T.BoxGeometry(w,h,d),new T.MeshStandardMaterial({color,roughness:.65}));o.position.set(x,y,z);g.add(o);return o;}
function ball(g,color,x,y,z,r){const o=new T.Mesh(new T.SphereGeometry(r,16,12),new T.MeshStandardMaterial({color,roughness:.6}));o.position.set(x,y,z);g.add(o);return o;}
for(let n=0;n<4;n++){const g=new T.Group();scene.add(g);models.push(g);if(n===0){box(g,'#fffdf5',0,1,0,1,1,5);box(g,'#ddece2',0,1,0,6,.22,1.2);box(g,'#6673a6',0,1,1.8,2.5,.2,.7);box(g,'#3f7278',0,1.5,1.8,.2,1.1,.8);ball(g,'#557b92',0,1,-1.5,.5);}else if(n===1||n===2){const count=n===1?3:1;for(let c=0;c<count;c++){const z=c*3.5;box(g,n===1?'#f7f5ef':'#f3e2de',0,1,z,1.9,1.3,3);box(g,'#3f7278',0,1.8,z,1.6,.65,1.8);box(g,'#bcd9dd',0,1.8,z-1,1.3,.45,.06);for(const x of [-1,1])for(const dz of [-.9,.9])ball(g,'#405958',x,.5,z+dz,.38);}}else{ball(g,'#efc7a9',0,3,0,.55);box(g,'#6673a6',0,1.9,0,.9,1.2,.6);box(g,'#ddece2',0,2,.5,.7,.9,.4);box(g,'#3f7278',-.28,.7,0,.33,1.2,.4);box(g,'#3f7278',.28,.7,0,.33,1.2,.4);box(g,'#efc7a9',-.65,1.9,0,.3,1,.3);box(g,'#efc7a9',.65,1.9,0,.3,1,.3);}}
map.addLayer({id:'travel-model',type:'custom',renderingMode:'3d',onAdd(map,gl){this.renderer=new T.WebGLRenderer({canvas:map.getCanvas(),context:gl,antialias:true});this.renderer.autoClear=false;},render(gl,args){
const p=position(segments[mode].points,progress),next=position(segments[mode].points,Math.min(1,progress+.005));const size=Math.max(.6,Math.min(22000,650000/Math.pow(2,map.getZoom())));const altitude=mode===0?size*(2+Math.sin(progress*Math.PI)*6):0;const R=6371008.8;let matrix;
if(args.defaultProjectionData.projectionTransition>0){matrix=new T.Matrix4().makeRotationY(p[0]*Math.PI/180).multiply(new T.Matrix4().makeRotationX(-p[1]*Math.PI/180)).multiply(new T.Matrix4().makeTranslation(0,0,1+altitude/R)).multiply(new T.Matrix4().makeRotationX(Math.PI/2)).multiply(new T.Matrix4().makeScale(1/R,1/R,1/R));}else{const c=M.MercatorCoordinate.fromLngLat(p,altitude),s=c.meterInMercatorCoordinateUnits();matrix=new T.Matrix4().makeTranslation(c.x,c.y,c.z).multiply(new T.Matrix4().makeRotationZ(Math.PI)).multiply(new T.Matrix4().makeRotationX(Math.PI/2)).multiply(new T.Matrix4().makeScale(-s,s,s));}
models.forEach((m,i)=>{m.visible=i===mode;m.rotation.y=Math.atan2(-(next[0]-p[0]),next[1]-p[1]);m.position.y=i===3&&playing?Math.abs(Math.sin(progress*100))*.2:0;});matrix.scale(new T.Vector3(size,size,size));camera.projectionMatrix=new T.Matrix4().fromArray(args.defaultProjectionData.mainMatrix).multiply(matrix);this.renderer.resetState();this.renderer.render(scene,camera);
}});
for(const [index,stop] of payload.stops.entries()){const pin=document.createElement('button');pin.className='pin';pin.setAttribute('aria-label',stop.name+'，查看地点');pin.onclick=()=>{pause();map.flyTo({center:stop.coordinate,zoom:16,pitch:55,duration:reduced?0:1000});$('#location-label').textContent=stop.name;};new M.Marker({element:pin}).setLngLat(stop.coordinate).addTo(map);}status();
map.once('idle',()=>{clearTimeout(timeout);$('#notice').hidden=true;document.querySelectorAll('button:disabled,input:disabled').forEach(b=>b.disabled=false);$('#play').disabled=!payload.legs.length;$('#progress').disabled=!payload.legs.length;$('#map').setAttribute('data-ready','true');window.webkit?.messageHandlers.journey.postMessage({type:'ready'});});
});
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{if(map.isStyleLoaded()){pause();setLevel(+b.dataset.level);exploreSheet.close();}});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>choose(+b.dataset.mode));$('#drill').onclick=()=>{pause();setLevel((level+1)%5);exploreSheet.close();};$('#overview').onclick=overview;$('#progress').oninput=e=>{pause();progress=Number(e.target.value)/1000;status();map.triggerRepaint();};$('#play').onclick=()=>{if(playing){pause();return;}if(progress===1)progress=0;setLevel(segments[mode].level);overview();playing=true;$('#play').textContent='Ⅱ';$('#play').setAttribute('aria-label','暂停旅程');last=performance.now();frame=requestAnimationFrame(tick);};document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('pagehide',()=>{pause();map.remove();});window.pauseJourney=pause;
}catch(e){window.webkit?.messageHandlers.journey.postMessage({type:'error',message:'三维地图加载失败，请重试或使用离线位置视图。'});console.error(e);}
