"""Mac plugin commands against real QuanSyn API, including scoped file transfer."""
import importlib.util
import json
import uuid
import asyncio
from pathlib import Path
from types import SimpleNamespace

import pytest
from fastapi.testclient import TestClient
from backend.api import quansyn as api
from backend.models.tenant import TenantMapping
from backend.db import SessionLocal
from backend.main import app
from backend.api.auth import require_auth
from backend.api.agreement import CURRENT_AGREEMENT_VERSION

SPEC = importlib.util.spec_from_file_location("quansyn_mac", Path(__file__).resolve().parents[1] / "agency/hermes-plugins/ai-lab-capabilities/quansyn.py")
MODULE = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(MODULE)


class State:
    def __init__(self, root):
        self.data_dir = root
        self.values = {}
    def get(self, key, fallback):
        return self.values.get(key, fallback).copy()
    def set(self, key, value):
        self.values[key] = value.copy()


@pytest.fixture
def runtime(tmp_path, monkeypatch):
    monkeypatch.setenv("AI_LAB_GENERATED_ARTIFACT_ROOT", str(tmp_path / "artifacts"))
    owner = {"tenant_key": "mac-test", "user_id": uuid.uuid4().hex}
    async def identity():
        return owner
    app.dependency_overrides[api.principal] = identity
    app.dependency_overrides[require_auth] = identity
    async def mapping():
        async with SessionLocal() as db:
            db.add(TenantMapping(user_id=owner["user_id"], tenant_key=owner["tenant_key"]))
            await db.commit()
    asyncio.run(mapping())
    client = TestClient(app)
    assert client.put("/api/v1/me/agreement-acceptance", json={"agreement_version": CURRENT_AGREEMENT_VERSION, "idempotency_key": str(uuid.uuid4()), "source": "web"}).status_code == 200
    plugin = MODULE.QuanSyn(SimpleNamespace(state=State(tmp_path / "plugin"), get_config=lambda key, default: "https://quansyn.test"), owner_check=lambda platform, sender: sender == "ou_owner")
    credentials = {}
    plugin.credentials = SimpleNamespace(get=lambda key: credentials[key], set=lambda key, value: credentials.update({key: value}))
    original_http = plugin.http
    def http(sender, method, path, *, payload=None, data=None, filename=None, public=False, sink=None):
        # Actual API/device principal, not an HTTP response stub.
        from urllib.parse import quote
        headers = {} if public else {"Authorization": "Bearer " + credentials[plugin.account(sender)], "X-QuanSyn-Sender": sender}
        if filename:
            headers["X-File-Name"] = quote(filename)
        if hasattr(data, "read"):
            stream = data
            data = iter(lambda: stream.read(1024 * 1024), b"")
        override = app.dependency_overrides.pop(api.principal, None)
        try:
            response = client.request(method, "/api/v1/quansyn" + path, json=payload, content=data, headers=headers)
        finally:
            if override:
                app.dependency_overrides[api.principal] = override
        if response.status_code >= 300:
            raise ValueError(f"HTTP {response.status_code}")
        if method == "GET" and path.startswith("/files/"):
            if sink is not None:
                import hashlib
                for chunk in response.iter_bytes(chunk_size=1024 * 1024):
                    sink.write(chunk)
                return hashlib.sha256(response.content).hexdigest()
            return response.content
        return response.json()
    plugin.http = http
    yield plugin, client, owner, original_http
    app.dependency_overrides.pop(api.principal, None)
    app.dependency_overrides.pop(require_auth, None)


def turn(plugin, text, session="feishu-session", sender="ou_owner"):
    kw = {"platform": "feishu", "sender_id": sender, "session_id": session, "turn_id": uuid.uuid4().hex}
    context = plugin.before_turn(text, **kw)
    return kw, context


def test_manual_mac_roundtrip(runtime):
    plugin, c, _, _ = runtime
    source = c.post("/api/v1/quansyn/files", content=b"Mac actual input", headers={"X-File-Name": "input.txt"}).json()
    request = c.post("/api/v1/quansyn/transfers", json={"request_id": uuid.uuid4().hex, "target": "mac", "text": "处理附件，生成回答与输出文件", "files": [{"artifact_id": source["artifact_id"]}]}).json()
    pair = c.post("/api/v1/quansyn/devices/pair").json()
    kw, _ = turn(plugin, "绑定 QuanSyn " + pair["code"])
    assert plugin.command(**kw)["success"]
    assert "已绑定" in plugin.finalize("fake model text", **kw)
    kw, _ = turn(plugin, "拉取并执行 QuanSyn " + request["id"])
    execution = plugin.command(**kw)
    assert execution["success"], execution
    file = Path(execution["goal"]["files"][0]["path"])
    assert file.read_bytes() == b"Mac actual input"
    output = Path(execution["goal"]["output_directory"]) / "result.txt"
    output.write_text("actual generated bytes", encoding="utf-8")
    assert plugin.outputs({"paths": [str(output)], "blocks": [{"kind": "chart", "labels": ["实测"], "values": [12]}]}, **kw)["success"]
    final = plugin.finalize("## 完整结果\n已处理附件。", **kw)
    assert "推送 QuanSyn" in final
    kw, _ = turn(plugin, "推送 QuanSyn " + request["id"] + " 附件 1")
    sent = plugin.command(**kw)
    assert sent["success"], sent
    result = [r for r in c.get("/api/v1/quansyn/transfers").json()["items"] if r["direction"] == "result"][0]
    assert result["text"] == "## 完整结果\n已处理附件。"
    assert result["blocks"][0]["values"] == [12]
    assert c.get("/api/v1/quansyn/files/" + result["files"][0]["artifact_id"]).content == b"actual generated bytes"
    assert plugin.command(**kw) == sent


def test_commands_require_gateway_identity_and_exact_human_message(runtime):
    plugin, _, _, _ = runtime
    assert plugin.before_turn("绑定 QuanSyn " + "x" * 32, platform="cli", session_id="s", sender_id="ou_owner") is None
    assert plugin.before_turn("正文引用：查看 QuanSyn", platform="feishu", session_id="s", sender_id="ou_owner") is None
    assert plugin.before_turn("查看 QuanSyn", platform="feishu", session_id="s") is None
    kw, _ = turn(plugin, "查看 QuanSyn")
    assert "未取得实际执行回执" in plugin.finalize("已处理并上传", **kw)
    with pytest.raises(ValueError):
        plugin.command(**{**kw, "turn_id": "forged"})
    with pytest.raises(ValueError):
        plugin.outputs({"paths": []}, **kw)


def test_output_path_and_symlink_fences(runtime, tmp_path):
    plugin, _, _, _ = runtime
    kw, _ = turn(plugin, "执行 QuanSyn qs_" + "a" * 32)
    plugin.turns[kw["session_id"]]["executing"] = True
    outside = tmp_path / "private.txt"
    outside.write_text("private")
    with pytest.raises(ValueError):
        plugin.outputs({"paths": [str(outside)]}, **kw)
    root = plugin.root("ou_owner", "qs_" + "a" * 32)
    link = root / "link.txt"
    link.symlink_to(outside)
    with pytest.raises(ValueError):
        plugin.outputs({"paths": [str(link)]}, **kw)
    with pytest.raises(ValueError):
        plugin.outputs({"paths": [], "blocks": [{"kind": "chart", "labels": ["x"], "values": []}]}, **kw)


def test_changed_output_is_not_published(runtime):
    plugin, c, _, _ = runtime
    request = c.post("/api/v1/quansyn/transfers", json={"request_id": uuid.uuid4().hex, "target": "mac", "text": "test"}).json()
    pair = c.post("/api/v1/quansyn/devices/pair").json()
    kw, _ = turn(plugin, "绑定 QuanSyn " + pair["code"])
    plugin.command(**kw)
    kw, _ = turn(plugin, "拉取并执行 QuanSyn " + request["id"])
    run = plugin.command(**kw)
    output = Path(run["goal"]["output_directory"]) / "out.txt"
    output.write_text("before")
    plugin.outputs({"paths": [str(output)]}, **kw)
    plugin.finalize("completed", **kw)
    output.write_text("after")
    kw, _ = turn(plugin, "推送 QuanSyn " + request["id"] + " 附件 1")
    assert not plugin.command(**kw)["success"]
    assert all(r["direction"] == "request" for r in c.get("/api/v1/quansyn/transfers").json()["items"])


def test_native_handler_requires_pre_tool_admission(runtime):
    plugin, _, _, _ = runtime
    kw, _ = turn(plugin, "查看 QuanSyn")
    handler_kw = {"session_id": kw["session_id"]}
    with pytest.raises(ValueError, match="可信"):
        plugin.command(**handler_kw)
    assert plugin.pre_tool("ai_lab_execute:quansyn", {"inputs": {"action": "command"}}, **{**kw, "turn_id": "wrong"})["action"] == "block"
    assert plugin.pre_tool("ai_lab_execute:quansyn", {"inputs": {"action": "command"}}, **kw) is None
    # No bound credentials: a real failed operation, but native admission reached the handler.
    assert plugin.command(**handler_kw)["success"] is False
    with pytest.raises(ValueError, match="可信"):
        plugin.command(**handler_kw)


def test_standalone_mac_package_uses_canonical_contract(tmp_path, monkeypatch):
    import builtins
    import importlib
    import shutil
    package = tmp_path / "quansyn_standalone"
    package.mkdir()
    (package / "__init__.py").write_text("")
    root = Path(__file__).resolve().parents[1]
    shutil.copyfile(root / "agency/hermes-plugins/ai-lab-capabilities/quansyn.py", package / "quansyn.py")
    shutil.copyfile(root / "backend/contracts/quansyn.py", package / "_quansyn_contract.py")
    monkeypatch.syspath_prepend(str(tmp_path))
    module = importlib.import_module("quansyn_standalone.quansyn")
    original_import = builtins.__import__
    def standalone_import(name, *args, **kwargs):
        if name == "backend" or name.startswith("backend."):
            raise ImportError("source repository unavailable")
        return original_import(name, *args, **kwargs)
    monkeypatch.setattr(builtins, "__import__", standalone_import)
    plugin = module.QuanSyn(SimpleNamespace(state=State(tmp_path / "state"), get_config=lambda key, default: "https://www.t-react.com"), owner_check=lambda platform, sender: sender == "ou_owner")
    kw, _ = turn(plugin, "执行 QuanSyn qs_" + "a" * 32)
    plugin.turns[kw["session_id"]]["executing"] = True
    assert plugin.outputs({"paths": [], "blocks": [{"kind": "chart", "labels": ["x"], "values": [12]}]}, **kw)["success"]
    with pytest.raises(ValueError):
        plugin.outputs({"paths": [], "blocks": [{"kind": "chart", "labels": ["x"], "values": []}]}, **kw)


@pytest.mark.parametrize("accepted", [False, True])
def test_mac_recovers_lost_import_confirmation_without_losing_local_content(runtime, accepted):
    plugin, c, _, _ = runtime
    receipt = c.post('/api/v1/quansyn/files', content=b'local copy survives', headers={'X-File-Name': 'retry.txt'}).json()
    row = c.post('/api/v1/quansyn/transfers', json={'request_id': uuid.uuid4().hex, 'target': 'mac', 'text': 'saved local goal', 'files': [{'artifact_id': receipt['artifact_id']}]}).json()
    pair = c.post('/api/v1/quansyn/devices/pair').json()
    kw, _ = turn(plugin, '绑定 QuanSyn ' + pair['code'])
    assert plugin.command(**kw)['success']
    original = plugin.http
    def lost_response(sender, method, path, **kwargs):
        if path.endswith('/imported') and not accepted:
            raise ValueError('confirmation response lost')
        response = original(sender, method, path, **kwargs)
        if path.endswith('/imported'):
            raise ValueError('confirmation response lost')
        return response
    plugin.http = lost_response
    with pytest.raises(ValueError, match='response lost'):
        plugin.pull('ou_owner', row['id'])
    assert bool(c.get('/api/v1/quansyn/transfers/' + row['id']).json()['files']) is (not accepted)
    assert c.get('/api/v1/quansyn/files/' + receipt['artifact_id']).status_code == (404 if accepted else 200)
    plugin.http = original
    recovered = plugin.pull('ou_owner', row['id'])
    assert recovered['imported'] and recovered['text'] == 'saved local goal'
    assert Path(recovered['files'][0]['path']).read_bytes() == b'local copy survives'
    assert c.get('/api/v1/quansyn/files/' + receipt['artifact_id']).status_code == 404


def test_feishu_cards_use_native_private_callback_and_sender(runtime):
    plugin, _, _, _ = runtime
    source = SimpleNamespace(platform="feishu", chat_type="dm", user_id="ou_owner", user_id_alt=None, chat_id="oc_private")
    adapter = object()
    gateway = SimpleNamespace(adapters={"feishu": adapter})
    event = SimpleNamespace(source=source, text="QuanSyn", raw_message=None)
    assert plugin.gateway(event, gateway) == {"action": "rewrite", "text": "查看 QuanSyn"}
    assert plugin.delivery["ou_owner"] == (adapter, "oc_private")
    command = "拉取并执行 QuanSyn qs_" + "a" * 32
    value = {"quansyn_command": command, "sender_id": "ou_owner"}
    event.text = "/card button " + json.dumps(value)
    assert plugin.gateway(event, gateway) is None  # Typed JSON is not a native callback.
    native = SimpleNamespace(action=SimpleNamespace(value=value), operator=SimpleNamespace(open_id="ou_owner"))
    event.raw_message = SimpleNamespace(event=native)
    assert plugin.gateway(event, gateway)["text"] == command
    native.operator.open_id = "ou_other"
    assert plugin.gateway(event, gateway)["action"] == "skip"
    native.operator.open_id = "ou_owner"
    source.chat_type = "group"
    assert plugin.gateway(event, gateway)["action"] == "skip"
    source.chat_type = "dm"
    value["quansyn_command"] = "绑定 QuanSyn secret"
    assert plugin.gateway(event, gateway)["action"] == "skip"


def test_pending_card_and_default_full_result_do_not_execute_twice(runtime):
    plugin, c, _, _ = runtime
    pair = c.post("/api/v1/quansyn/devices/pair").json()
    kw, _ = turn(plugin, "绑定 QuanSyn " + pair["code"])
    assert plugin.command(**kw)["success"]
    request = c.post("/api/v1/quansyn/transfers", json={"request_id": uuid.uuid4().hex,
        "direction": "request", "target": "mac", "text": "分析实际数据并生成文件", "files": []}).json()
    transfer = request["id"]
    kw, _ = turn(plugin, "查看 QuanSyn")
    assert plugin.command(**kw)["success"]
    pending = plugin.card(plugin.turns[kw["session_id"]])
    buttons = [b for e in pending["elements"] if e["tag"] == "action" for b in e["actions"]]
    assert any(b.get("value", {}).get("quansyn_command") == "拉取并执行 QuanSyn " + transfer for b in buttons)
    kw, _ = turn(plugin, "拉取并执行 QuanSyn " + transfer)
    assert plugin.command(**kw)["goal"]["request"] == request["text"]
    path = plugin.root("ou_owner", transfer) / "analysis.csv"
    path.write_text("月份,数量\n一月,12\n")
    plugin.outputs({"paths": [str(path)], "blocks": [{"kind": "code", "content": "print(12)"}]}, **kw)
    plugin.finalize("真实执行结果", **kw)
    kw, _ = turn(plugin, "执行 QuanSyn " + transfer)
    result = plugin.command(**kw)
    assert result["success"] and "goal" not in result
    kw, _ = turn(plugin, "推送 QuanSyn " + transfer)
    assert plugin.command(**kw)["success"]
    rows = c.get("/api/v1/quansyn/transfers").json()["items"]
    published = next(x for x in rows if x["reply_to"] == transfer)
    assert len(published["files"]) == 1 and published["blocks"][0]["kind"] == "code"
    assert c.get("/api/v1/quansyn/files/" + published["files"][0]["artifact_id"]).content == path.read_bytes()


def test_card_delivery_uses_existing_adapter_loop_and_falls_back(runtime):
    import threading
    plugin, _, _, _ = runtime
    loop = asyncio.new_event_loop()
    ready = threading.Event()
    def run():
        asyncio.set_event_loop(loop)
        loop.call_soon(ready.set)
        loop.run_forever()
    worker = threading.Thread(target=run)
    worker.start(); assert ready.wait(3)
    sent = []
    async def send(**kw):
        sent.append(kw)
        return SimpleNamespace(success=True)
    adapter = SimpleNamespace(_loop=loop, _feishu_send_with_retry=send,
        _finalize_send_result=lambda response, error: response)
    plugin.delivery["ou_owner"] = (adapter, "oc_private")
    turn = {"sender": "ou_owner", "action": "查看", "rows": [], "reply": "暂无需求"}
    try:
        assert plugin.deliver_card(turn)
        assert sent[0]["chat_id"] == "oc_private" and sent[0]["msg_type"] == "interactive"
        card = json.loads(sent[0]["payload"])
        assert card["header"]["title"]["content"] == "Quantum · QuanSyn"
        adapter._finalize_send_result = lambda response, error: SimpleNamespace(success=False)
        assert plugin.deliver_card(turn) is False
    finally:
        loop.call_soon_threadsafe(loop.stop);worker.join(3);loop.close()


def test_mac_requires_existing_host_owner_policy(runtime):
    plugin, _, _, _ = runtime
    assert plugin.before_turn("查看 QuanSyn", platform="feishu", session_id="foreign", sender_id="ou_other") is None
    unconfigured = MODULE.QuanSyn(plugin.ctx)
    assert unconfigured.before_turn("查看 QuanSyn", platform="feishu", session_id="s", sender_id="ou_owner") is None


def test_mac_large_attachment_roundtrip_and_server_cleanup(runtime):
    import hashlib
    import shutil
    plugin, c, _, _ = runtime
    raw = b"actual-transfer-integrity\n" * (27 * 1024 * 1024 // 26 + 1)
    assert len(raw) > 25 * 1024 * 1024
    source = c.post("/api/v1/quansyn/files", content=raw, headers={"X-File-Name": "large.txt"}).json()
    request = c.post("/api/v1/quansyn/transfers", json={"request_id": uuid.uuid4().hex,
        "target": "mac", "text": "完整传输和处理附件", "files": [{"artifact_id": source["artifact_id"]}]}).json()
    pair = c.post("/api/v1/quansyn/devices/pair").json()
    kw, _ = turn(plugin, "绑定 QuanSyn " + pair["code"])
    assert plugin.command(**kw)["success"]
    kw, _ = turn(plugin, "拉取并执行 QuanSyn " + request["id"])
    execution = plugin.command(**kw)
    assert execution["success"], execution
    path = Path(execution["goal"]["files"][0]["path"])
    with path.open("rb") as stream:
        assert hashlib.file_digest(stream, "sha256").hexdigest() == hashlib.sha256(raw).hexdigest()
    row = c.get("/api/v1/quansyn/transfers/" + request["id"]).json()
    assert row["text"] == "" and row["files"] == []
    assert c.get("/api/v1/quansyn/files/" + source["artifact_id"]).status_code == 404
    output = path.parent / "processed.txt"
    shutil.copyfile(path, output)
    plugin.outputs({"paths": [str(output)]}, **kw)
    plugin.finalize("附件处理完成", **kw)
    kw, _ = turn(plugin, "推送 QuanSyn " + request["id"])
    assert plugin.command(**kw)["success"]
    result = next(r for r in c.get("/api/v1/quansyn/transfers").json()["items"] if r["reply_to"] == request["id"])
    assert hashlib.sha256(c.get("/api/v1/quansyn/files/" + result["files"][0]["artifact_id"]).content).hexdigest() == hashlib.sha256(raw).hexdigest()
