import os,pathlib,pwd,subprocess,json
pid=subprocess.check_output(['systemctl','show','hermes-bridge.service','-p','MainPID','--value'],text=True).strip()
current=dict(x.split('=',1) for x in pathlib.Path('/proc/'+pid+'/environ').read_text().split('\0') if '=' in x)
u=pwd.getpwnam('quantumn-hermes'); root=pathlib.Path('/tmp/travel-cloud-browser-r3pqziwo')
env={k:current[k] for k in ('HTTP_PROXY','HTTPS_PROXY','NO_PROXY','LANG') if k in current}
env.update(HOME=str(root),HERMES_HOME=str(root/'hermes'),PATH=str(root/'runtime/node_modules/.bin')+':/var/lib/quantumn-hermes/.hermes/node/bin:/usr/bin:/bin',AGENT_BROWSER_EXECUTABLE_PATH=str(root/'.agent-browser/browsers/chrome-154.0.8037.57/chrome'),AGENT_BROWSER_PROXY=current.get('HTTPS_PROXY',''),HERMES_BROWSER_TIMEOUT='25',LD_LIBRARY_PATH=str(root/'libs/usr/lib/x86_64-linux-gnu'))
code='import sys,json,time,re\nsys.path.insert(0,"/var/lib/quantumn-hermes/.hermes/hermes-agent")\nfrom tools.browser_tool import browser_navigate,browser_snapshot,browser_click,browser_type,browser_press,browser_vision\nfrom tools.browser_tool_lifecycle import cleanup_browser\ntask="travel-maps-date-acceptance"\ndef snap():\n r=json.loads(browser_snapshot(task_id=task));print("snapshot",json.dumps(r,ensure_ascii=False),flush=True);return r.get("snapshot","")\ntry:\n for attempt in range(2):\n  nav=json.loads(browser_navigate("https://www.google.com/maps/dir/?api=1&origin=Tokyo+Station&destination=Shinjuku+Station&travelmode=transit&hl=en",task_id=task));print("navigate",json.dumps(nav,ensure_ascii=False),flush=True)\n  if nav.get("success"):break\n  time.sleep(2)\n if not nav.get("success"):raise RuntimeError("maps_navigation_failed")\n time.sleep(2);page=snap()\n match=re.search(r\'button "Leave now" \\[ref=(e\\d+)\\]\',page)\n if match:\n  print("click",browser_click("@"+match[1],task_id=task),flush=True);time.sleep(1);page=snap()\n  choice=re.search(r\'[^\\n]*"Depart at"[^\\n]*ref=(e\\d+)\',page)\n  if choice:\n   print("depart_at",browser_click("@"+choice[1],task_id=task),flush=True);time.sleep(1);page=snap()\n next_day=re.search(r\'button "[^"\\n]*Go to the next day" \\[ref=(e\\d+)\\]\',page)\n if next_day:\n  print("next_day",browser_click("@"+next_day[1],task_id=task),flush=True);time.sleep(2);page=snap()\n  field=re.search(r\'textbox \\[ref=(e\\d+)\\]:\',page)\n  if field:\n   print("time",browser_type("@"+field[1],"9:00 AM",task_id=task),flush=True)\n   print("apply",browser_press("Enter",task_id=task),flush=True);time.sleep(3);page=snap()\n print("dated_route_verified", "Mon, Sep 28" in page and "Chūō" in page,flush=True)\n result=browser_vision("Describe this public transit route page without interacting.",task_id=task)\n r=json.loads(result) if isinstance(result,str) else result\n path=r.get("screenshot_path") or r.get("meta",{}).get("screenshot_path")\n print("screenshot",json.dumps({"success":r.get("success"),"path":path,"error":r.get("error")},ensure_ascii=False),flush=True)\nfinally:cleanup_browser(task_id=task)\n'
r=subprocess.run(['/var/lib/quantumn-hermes/bridge-worker-venv/bin/python','-c',code],env=env,cwd=root,user=u.pw_uid,group=u.pw_gid,timeout=110,capture_output=True,text=True)
(root/'maps-date-result.txt').write_text(r.stdout+'\n'+r.stderr)
print(r.stdout[-14000:]); print(r.stderr[-2000:]);print('exit',r.returncode)
